### ISSUE TITLE
Cannot edit categories when adding/editing article

### ISSUE THREAD

**Issue by thomas1983** [themebright/HelpPress#13]
I work on WordPress 5.2.4

Since the update of Helppress to the latest version it seems the category widget has disappeared from the editing page.

I solved this temporarily by making the article, going to all articles, selecting the article en selecting edit from the jump menu and proceed from there.

**Comment by galengidman** [comment]
Thanks for alerting me to this @thomas1983. Fixed in the `3.1.3` which is now available.
